kind: Service
apiVersion: v1
metadata:
  name:  myservice
  labels:
     app: myspringbootapp
spec:
  selector:
    app: myspringbootapp
  type:  LoadBalancer
  ports:
   - port:  8080
     targetPort:  9090